config/routes.rb
Seva::Application.routes.draw do

  resources :posts, :charges, :static_pages

  devise_for :users

  root :to => "static_pages#home"

  get "path", to: 'controller#action', as: :name_of_path

  get "home", to:  "static_pages#home", as: :home
  get "about", to:  "static_pages#about", as: :about
  get "pricing", to: "static_pages#pricing", as: :pricing
  get "data", to: "static_pages#data", as: :data
  get "legal", to: "static_pages#legal", as: :legal
  get "posts", to: "posts#index", as: :posts
  get "contact_me", to: 'contact_me#new', as: :contact_me
  post "contact_me", to: 'contact_me#create', as: :contact_me

  

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :about, :contact, :home, :pricing
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_filter :authenticate_user!, :user_has_subscription, only: :data
def data
  @players = Player.where(nil)
  if params[:class].present?
    @players = @players.where(klass: params[:class])
  end
  if params[:state].present?
    @players = @players.where(state: params[:state])
  end
  if params[:score].present?
    @players = @players.where("seva_score >= ?", params[:score])
  end
  if params[:height].present?
    @players = @players.where("height >= ?", params[:height])
  end
  if params[:ppg].present?
    @players = @players.where("ppg >= ?", params[:ppg])
  end
  if params[:fg_percent].present?
    @players = @players.where("fg_percent >= ?", params[:fg_percent])
  end
  @players = @players.to_a
end


  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end

  private
  def user_has_subscription
    redirect_to root_url, alert: "You're not a subscriber" unless current_user.stripe_customer_id.present?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :pricing %><br />
    <%= f.text_field :pricing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/_modal.html.erb
<div>
  <p> THIS IS MY MODAL </p>
</div

app/views/static_pages/about.html.erb
<h1>About SEVA</h1>

<p>We have all the stats you want in one place.  SEVA knows that coaches have limited time to watch, evaluate, and recruit players.  We makes coaches’ lives easier by filtering and sorting data from over 30,000 players.

SEVA also helps you with some elite statistical analysis.  Our SEVA Score takes into account a player’s on court performance, team performance, and personal information to produce an overall recruit rating.  Check out other analysis such as our Estimated Position and Scoring Breakdown.</p>

</br>
</br>
<h2>Here is a Sample of how SEVA works</h2>
</br>
</br>
<table id="previous-players">
  <thead>
    <tr>
      <td>Player</td>
      <td>College</td>
      <td>SEVA Score</td>
      <td>Scout Star Rating</td>
      <td>Rivals Star Rating</td>
      <td>ESPN Star Rating</td>
      <td>ESPN Rating</td>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>Jimmer Fredette</td>
    <td>BYU</td>
    <td>9.31</td>
    <td>2</td>
    <td>3</td>
    <td>*</td>
    <td>79</td>
  </tr>
  <tr>
    <td>Kelly Olynyk</td>
    <td>Gonzaga</td>
    <td>9.57</td>
    <td>0</td>
    <td>0</td>
    <td>*</td>
    <td>90</td>
  </tr>
  <tr>
    <td>Damian Lillard</td>
    <td>Weber St.</td>
    <td>4.36</td>
    <td>0</td>
    <td>0</td>
    <td>0</td>
    <td>85</td>
  </tr>
  <tr>
    <td>Keala King</td>
    <td>Arizona St/Long Beach St</td>
    <td>5.21</td>
    <td>4</td>
    <td>5</td>
    <td>4</td>
    <td>95</td>
  </tr>
  <tr>
    <td>CJ McCollum</td>
    <td>Lehigh</td>
    <td>9.09</td>
    <td>2</td>
    <td>0</td>
    <td>*</td>
    <td>83</td>
  </tr>
  <tr>
    <td>Ron Baker</td>
    <td>Witchita St.</td>
    <td>8.19</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>NR</td>
  </tr>
  <tr>
    <td>Demarcus Harrison</td>
    <td>BYU/Clemson</td>
    <td>2.33</td>
    <td>2</td>
    <td>4</td>
    <td>3</td>
    <td>91</td>
  </tr>
  <tr>
    <td>Jaycee Carroll</td>
    <td>Utah St</td>
    <td>9.27</td>
    <td>0</td>
    <td>0</td>
    <td>*</td>
    <td>*</td>
  </tr>
  <tr>
    <td>Josiah Turner</td>
    <td>Arizona</td>
    <td>6.11</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>97</td>
  </tr>
  <tr>
    <td>Kenneth Faried</td>
    <td>Morehead St.</td>
    <td>8.19</td>
    <td>0</td>
    <td>0</td>
    <td>*</td>
    <td>75</td>
  </tr>
  <tr>
    <td>Travis Wear</td>
    <td>North Carolina/UCLA</td>
    <td>5.21</td>
    <td>4</td>
    <td>4</td>
    <td>4</td>
    <td>94</td>
  </tr>
 </tbody>
</table>

</br>
</br>
</br>
</br>

<h2>What the numbers mean?</h2>
<%= image_tag ('SEVA_Score_Graphic.png'), class: 'image-responsive' %>
</br>
</br>
</br>
</br>


<h2>FAQ</h2>

<h3>How is a SEVA Score calculated?</h3>
<p>SEVA uses advanced statistical methods in the calculation of SEVA Scores. While the details of these methods are kept proprietary, we do note that SEVA only uses information that is relevant to the on-court performance of each player. In calculating SEVA Scores, we make use of individual box score statistics (such as PPG and RPG), team level performance (such as Win% and Division) as well as pertinent player information (such as height and class).</p>
</br>
</br>
<h3>What if a SEVA Score is lower than the level of recruitment for a given player?</h3>
<p>The following are possible explanations for such a scenario:
	•	Recruiters/Coaches see potential above and beyond that player’s performance. They  may believe the player will be able to develop into a better player than what past performance has shown.
	•	The player may have positive characteristics that are not measured on the court (i.e. grades, character, etc.).
	•	The player’s perceived level of interest may be overestimated. Recruiting interest can be identified as serious when coaches have offered scholarships, made personal phone calls, or paid in-home visits.</p>
</br>
</br>

<h3>What if a player’s SEVA Score is high, but the player is not receiving high interest from elite schools?</h3>
<p>It is difficult to say why college coaches have not shown as much interest as the player’s performance would suggest. The following are possible explanations:
	<ul>
	<li>The player is undervalued and have been overlooked by coaches.</li>
	<li>Coaches may believe that the player’s performance has been great, but that his game will not translate to the next level.</li>
	<li>Coaches may believe that the player has maximized his potential and does not have much room to improve.</li>
	<li>Coaches may believe that the player’s off-court skills are not adequate (i.e. grades, character, etc.)</li>
	</ul></p>
</br>
</br>
<h3>Do SEVA Scores account for club (AAU) performance?</h3>
<p>Currently, club basketball tournaments do not provide statistics that are accurate enough to incorporate into SEVA's models. Knowing that club basketball is becoming the lifeblood of college basketball recruiting, we are working to improve the accuracy of statistics at this level and thus improve the SEVA model by incorporating this information.
How can a player improve his SEVA Score?
There are various ways that a player can increase his SEVA Score, including scoring more points per game, winning more games, or dishing out a few more assists. It is different for every player.</p>
</br>
</br>
<h3>From where does SEVA get data?</h3>
<p>SEVA gathers data from various media sources.  Most high schools send box score and game information to newspapers, online media sites, and other sources.  SEVA collaborates with these sources to provide a one-stop database for high school basketball stats.</p>
</br>
</br>
<h3>Is SEVA’s data 100% accurate?</h3>
<p>While we cannot guarantee 100% accuracy, we know that our data is very close.  Discrepancies may come from misreporting of data, typos, or other minor mistakes.  These errors are very minor and typically negligible.  If you come across an error, please notify us at contact@SEVASPORTS.com </p>
</br>
</br>
<p class= "quote"><strong>Rick Majerus,</strong> commenting about preparing to face Kentucky in the national championship, stated, “They have all those McDonald’s All-Americans.  We have 4 guys on our team who don’t even have a McDonalds in their town.”</p>

</br>
</br>

<script>
  $('#previous-players').dataTable({
    "sPaginationType": "bootstrap"
  });
</script>

app/views/static_pages/data.html.erb
<table id="players">
    <thead>
     <tr>
      <td>Rank</td>
      <td>Name </td>
      <td>State</td>
      <td>Class</td>
      <td>Year</td>
      <td>Seva Score</td>
      <td>Team</td>
      <td>Win%</td>
      <td>Height</td>
      <td>Weight</td>
      <td>PPG</td>
      <td>FG%</td>
      <td>APG</td>
      <td>BPG</td>
      <td>RPG</td>
      <td>SPG</td>
      <td>College</td>
     </tr>
    </thead>
    <tbody>
    <% @players.each do |player| %>
    <tr>
      <td><%= player.rank %></td>
      <td ><%= player.name %></td>
      <td><%= player.state %></td>
      <td><%= player.klass %></td>
      <td><%= player.year %></td>
      <td><%= player.seva_score %></td>
      <td><%= player.team %></td>
      <td><%= player.win_percent %></td>
      <td><%= player.height %></td>
      <td><%= player.weight %></td>
      <td><%= player.ppg %></td>
      <td><%= player.fg_percent %></td>
      <td><%= player.apg %></td>
      <td><%= player.bpg %></td>
      <td><%= player.rpg %></td>
      <td><%= player.spg %></td>
      <td><%= player.college %></td>
     </tr>
    <% end %>
  </tbody>
</table>
<div>


  <div class= "col-md-5">
    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "class", options_for_select([ " Freshman", " Sophomore", " Junior", " Senior" ], " Junior") %></br>
    <%= submit_tag "Filter by Class" , class: "btn btn-primary" %>
    <%end%>

    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "state", options_for_select(FormUtilities.us_states.map) %></br>
    <%= submit_tag "Filter by State" , class: "btn btn-primary" %>
    <%end%>

    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "score", options_for_select(0..10) %></br>
    <%= submit_tag "Filter SEVA score" , class: "btn btn-primary" %>
    <%end%>
  </div>
  <div class= "col-md-5">
    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "height", options_for_select(60..90) %></br>
    <%= submit_tag "Filter by Height (in inches)" , class: "btn btn-primary"  %>
    <%end%>

    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "ppg", options_for_select(1..50) %></br>
    <%= submit_tag "Filter PPG" , class: "btn btn-primary" %>
    <%end%>

    <%= form_tag(data_path, method: :get) do %>
    <%= select_tag "fg_percent", options_for_select(1..100) %></br>
    <%= submit_tag "Filter by FG%" , class: "btn btn-primary" %>
    <%end%>
  </div>
</div>


<script>
  $('#players').dataTable({
    "sPaginationType": "bootstrap"
  });
</script>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/home.html.erb
<p><%= image_tag ('TempleBball.jpg'), class: 'img-responsive' %></p>


<h1>Welcome to SEVA Sports!</h1>

<div>
  <div class='col-sm-4'>
    <div class='thumbnail text-center'>
      <h2 class="glyphicon glyphicon-search"></h2>
      <h5>Search 30k+ players</h5>
      <p>We gather data from high school coaches</p></br></br>
    </div>
  </div>
  <div class='col-sm-4'>
    <div class='thumbnail text-center'>
      <h2 class="glyphicon glyphicon-search"></h2>
      <h5>Statistically compare players</h5>
      <p>We statistically evaluate every player, so you don't have to. All you have to do is compare the players you like</p>
    </div>
  </div>
    <div class='col-sm-4'>
      <div class='thumbnail text-center'>
      <h2 class="glyphicon glyphicon-eye-open"></h2>
      <h5>Recruit only the best</h5>
      <p>After you have cut through the fluff, or found that diamond in the rough, its game on.</p></br>
    </div>
    </br>
    </br>
    </br>
    </br>
  </div>
</div>

 

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <tr>
    <th>Home</th>
    <th>About</th>
    <th>Contact</th>
    <th>Pricing</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_pages.each do |static_page| %>
  <tr>
    <td><%= static_page.home %></td>
    <td><%= static_page.about %></td>
    <td><%= static_page.contact %></td>
    <td><%= static_page.pricing %></td>
    <td><%= link_to 'Show', static_page %></td>
    <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
    <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/legal.html.erb
<h2>Legal Notice</h2>
<div class= 'legal'>
  
<p><span><strong>Legal</strong></span></br>
The terms “the company”, “we”, and “us” refer to SEVA Sports.  The terms “you”, “user”, and “subscriber” refer to users of the website and it’s services.</p>

<p><span><strong>Use of Services</strong></span></br>
Use of this site is without warranty and in an as-is condition and on an as available basis.  The Web Site does not guarantee the accuracy or reliability of the information presented on this website.  Errors, discrepancies, or mistakes may occur and the company is not held liable for such.

Users are responsible for maintaining the confidentiality of personal login names and passwords.  Users must accept responsibility for all activities, charges, and damages that occur under your account.

The content, information, data, designs, code, and materials pertaining to this website are protected by intellectual property and other laws. Users are required to comply with all such laws and applicable copyright, trademark or other legal notices or restrictions.

Subject to these Terms, users may access and use the Services only for use. We reserve all other rights to the services and content of this website, and users may not otherwise copy, reproduce, distribute, publish, display, perform, or create derivative works of said services or content without our permission. Users also may not transfer or sublicense this limited right to use the services or resell the services.

The company, and this website, does not represent or warrant that the site or users use of the site will be uninterrupted, free of errors, free of defects, or will operate with all software.</p>

<p><span><strong>Liability</strong></span></br>
The company, and this website, will not be liable to users (registered or unregistered) or any other third party for consequential, incidental, indirect, punitive, or special damages.

Users hereby agree that by use of this site, to be governed by the Laws of the State of Utah.  Any and all actions or claims will be brought in a court of competent jurisdiction within the borders of the State of Utah at the court closest to the company headquarters, or another reasonable location named by the company’s managers.</p>

<p><span><strong>Force Majeure</strong></span></br>
The company, and this website, will not be liable for failing to perform under these terms of use by the occurrence of any event beyond its reasonable control, including, without limitation, a labor disturbance, an Internet outage or interruption of service, a communications outage, failure by a service provider to the website to perform, fire, terrorism, natural disaster or war, or other event outside the control of the company.</p>

<p><span><strong>Subscriptions</strong></span></br>
A “team subscription” is granted on an individual team basis and is granted for the use of that team only.  The use is limited to coaches, managers, video coordinators, and scouts only.  Team subscriptions are non-transferrable and cannot be shared or distributed in any way.

An “individual subscription” is granted on an individual basis and is granted for the use of that person only.  The use is limited to that individual only.  Individual subscriptions are non-transferrable and cannot be shared or distributed in any way.

All subscriptions are granted on monthly or annual basis.  Subscriptions are non-recurring, and will expire one year or one month (depending on the type) from their purchase.

All subscription fees are non-refundable. The company reserves the right to make changes to its content at any time. If the company temporarily reduces or eliminates the charge for content or access that users are currently paying for under different terms, users will not receive a refund.
</p>
  
</div>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/pricing.html.erb
<H1>Pricing</H1>
</br>

<div class='col-sm-4'>
  <div class='thumbnail text-center'>
    <h2>Bronze</h2>
    <h4>$50/mo.</h4></br>
    <p>Access to ALL the SEVA players in your State</p>
    <%= simple_form_for :plan, url: charges_path do  |f| %>
      <%= f.input :id, as: :hidden, input_html: {value: 'bronze'} %> 
      <div class='stripe-script'>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Bronze Plan"
                data-amount="5000"></script>
      </div>
    <% end %>
  </div>
</div>
<div class='col-sm-4'>
  <div class='thumbnail text-center'>
    <h2>Silver</h2>
    <h4>$500/mo.</h4></br>
    <p>Access to ALL the SEVA players in your Conference</p>
    <%= simple_form_for :plan, url: charges_path do  |f| %>
      <%= f.input :id, as: :hidden, input_html: {value: 'silver'} %> 
      <div class='stripe-script'>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Silver Plan"
                data-amount="50000"></script>
      </div>
    <% end %>
  </div>
</div>
<div class='col-sm-4'>
  <div class='thumbnail text-center'>
    <h2>Gold</h2>
    <h4>$5,000/mo.</h4>
    <p>Access to ALL the SEVA players, and a signed photograph of BYU legend, Chris Colinsworth</p>
    <%= simple_form_for :plan, url: charges_path do  |f| %>
      <%= f.input :id, as: :hidden, input_html: {value: 'gold'} %> 
      <div class='stripe-script'>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Gold Plan"
                data-amount="500000"></script>
      </div>
    <% end %>
  </div>
</div>
  

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Home:</b>
  <%= @static_page.home %>
</p>

<p>
  <b>About:</b>
  <%= @static_page.about %>
</p>

<p>
  <b>Contact:</b>
  <%= @static_page.contact %>
</p>

<p>
  <b>Pricing:</b>
  <%= @static_page.pricing %>
</p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>