config/routes.rb
Seva::Application.routes.draw do

  resources :posts, :charges, :static_pages

  devise_for :users

  root :to => "static_pages#home"

  get "path", to: 'controller#action', as: :name_of_path

  get "home", to:  "static_pages#home", as: :home
  get "about", to:  "static_pages#about", as: :about
  get "pricing", to: "static_pages#pricing", as: :pricing
  get "data", to: "static_pages#data", as: :data
  get "legal", to: "static_pages#legal", as: :legal
  get "posts", to: "posts#index", as: :posts
  get "contact_me", to: 'contact_me#new', as: :contact_me
  post "contact_me", to: 'contact_me#create', as: :contact_me

  

end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container text-center'>
    <nav class="navbar" role="footer">
    <p>&copy; <%= Time.now.year %> <%= link_to ("SEVA Sports."), legal_path %> All rights reserved </p>
    </nav>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" > 
  <div>
    <ul class="nav navbar-nav">
      <li><%= link_to (image_tag ('logo.png')), root_path, class: "navbar-brand navbar-btn" %></li>
      <li><%= link_to t(:about), about_path, class: "navbar-btn" %></li>
      <li><%= link_to t(:contact), contact_me_path, class: "navbar-btn" %></li>
      <li><%= link_to t(:pricing), pricing_path, class: "navbar-btn" %></li>
      <li><%= link_to t(:data), data_path, class: "navbar-btn" %></li>
      <li><%= link_to t(:posts), posts_path, class: "navbar-btn" %></li>
    </ul> 
  </div>
  <div>
  <ul class="nav navbar-inverse navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Signed in as #{current_user.email}, Sign Out", destroy_user_session_path, method: :delete, class: "navbar-btn" %></li>
      <% else %>
        <li><%= link_to "GET STARTED", new_user_registration_path, class: "navbar-btn", id: "sevablue-btn" %></li> 
        <li><%= link_to "LOGIN", new_user_session_path, class: "navbar-btn", id: "sevablue-btn" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seva</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>
<body class= 'main-body' >
  <div class= 'container'>
  
   <%= render 'layouts/navigation' %>
   <%= render 'layouts/messages' %>
   <%= yield %>
  </div>
</body>
<%= render 'layouts/footer' %>
</html>